# Generated by Django 3.2.7 on 2022-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='degree_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
