# Generated by Django 3.2.7 on 2022-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_degree_degree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='fourth_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='third_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
