# Generated by Django 3.2.7 on 2022-03-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_paper_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='date_of_Publishing',
            new_name='date_of_publishing',
        ),
    ]
