# Generated by Django 3.2.7 on 2022-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_rename_date_of_publishing_paper_date_of_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='supervisor',
            field=models.ManyToManyField(blank=True, to='papers.Supervisor'),
        ),
        migrations.DeleteModel(
            name='PaperSupervisor',
        ),
    ]
