-- // cleaning supervisor //--
update papers_all set supervisor ='بابكر البدوي دشين' where supervisor like '%بابكر البدوي دوشين%';
update papers_all set supervisor ='بابكر البدوي دشين' where supervisor like '%بابكر بدوي دشين%';
update papers_all set supervisor ='بابكر حسن محمد قدرماري' where supervisor like '%بابكر حسن %';
update papers_all set supervisor ='بابكر حسن محمد قدرماري' where supervisor like '%بابكر قدر ماري%';
update papers_all set supervisor ='بابكر حسن محمد قدرماري' where supervisor like '%بابكر قدري ماري%';
update papers_all set supervisor ='بشرى السيد محمد هاشم' where supervisor like '%برشرى السيد محمد هاشم%';
update papers_all set supervisor ='بشرى السيد محمد هاشم' where supervisor like '%بشرى السيد هاشم%';
update papers_all set supervisor ='تغريد السيد عنبر' where supervisor like '%تغريد عنبر%';
update papers_all set supervisor ='تماضر حمزة محمد فضل' where supervisor like '%تماضر حمزة محمد%';
update papers_all set supervisor ='حامد محمد ابراهيم محمد' where supervisor like '%حامد محمد إبراهيم%';
update papers_all set supervisor ='حربية محمد أحمد عثمان' where supervisor like '%حربية محمد أحمد%';
update papers_all set supervisor ='حربية محمد أحمد عثمان' where supervisor like '%حربيسة محمد أحمد%';
update papers_all set supervisor ='حسن الفضل علي محمد' where supervisor like '%حسن الفضل%';
update papers_all set supervisor ='حسن عبد الرحمن الحسن' where supervisor like '%حسن عبد الرحمن حسن%';
update papers_all set supervisor ='حسن علي الشايقي' where supervisor like '%حسن على الشايقي%';
update papers_all set supervisor ='حسن علي عيسى' where supervisor like '%حسن على عيسى%';
update papers_all set supervisor ='حسن منصور أحمد سوركتي' where supervisor like '%حسن منصور سوركتي%';
update papers_all set supervisor ='حمد النيل محمد الحسن إبراهيم' where supervisor like '%حمد النيل محمد الحسن%';
update papers_all set supervisor ='حمد النيل محمد الحسن إبراهيم' where supervisor like '%حمد النيل محمد حسن%';
update papers_all set supervisor ='حياة عبد الوهاب التهامي' where supervisor like '%حياة عبد الوهاب%';
update papers_all set supervisor ='رقية السيد الطيب العباس' where supervisor like '%رقية السيد%';
update papers_all set supervisor ='زكريا علي أحمد' where supervisor like '%زكريا على أحمد%';
update papers_all set supervisor ='سعاد عبد الرحيم البشير' where supervisor like '%سعاد عبد الرحيم%';
update papers_all set supervisor ='سعيد حواية الله أحمد' where supervisor like '%سعيد حواية الله%';
update papers_all set supervisor ='سلوى عثمان أحمد محمد' where supervisor like '%سلوى عثمان أحمد%';
update papers_all set supervisor ='عبد الرحمن عبد الله الخانجي' where supervisor like '%عبد الرحمن عبد الخانجي%';
update papers_all set supervisor ='عبد الرحمن محمد أحمد كدوك' where supervisor like '%عبد الرحمن كدوك%';
update papers_all set supervisor ='عبد الرحمن محمد أحمد كدوك' where supervisor like '%عبد الرحمن محمد احمد كدوك%';
update papers_all set supervisor ='عبد الرحمن محمد أحمد كدوك' where supervisor like '%عبد الرحمن محمد كدوك%';
update papers_all set supervisor ='عبد القادر أحمد الشيخ الفادني' where supervisor like '%عبد القادر أحمد شيخ الفادني%';
update papers_all set supervisor ='عبد القادر عثمان محمد جاد الرب' where supervisor like '%عبد القادر عثمان محمج جاد الرب%';
update papers_all set supervisor ='عبد القادر عثمان محمد جاد الرب' where supervisor like '%عبد القادر عثمان%';
update papers_all set supervisor ='عبد القادر قسم السيد الدابي' where supervisor like '%عبد القادر قسم السيد%';
update papers_all set supervisor ='عبد القادر قسم السيد الدابي' where supervisor like '%عبد القادر السيد الدابي%';
update papers_all set supervisor ='عبد الرحمن عبد الله الخانجي' where supervisor like '%عبد الله الخانجي%';
update papers_all set supervisor ='عبد الله محمد أحمد' where supervisor like '%عبد الله محمد احمد%';
update papers_all set supervisor ='عبد الله محمد عبد الله عجبنا' where supervisor like '%عبد الله محمد عجبنا%';
update papers_all set supervisor ='عبد الله محمد عبد الله عجبنا' where supervisor like '%عبدالله محمد عبدالله عجبنا%';
update papers_all set supervisor ='عثمان عبدالله ضيف الله' where supervisor like '%عثمان عبدالل ضيف الله%';
update papers_all set supervisor ='علي أحمد محمد بابكر' where supervisor like '%على أحمد محمد بابكر%';
update papers_all set supervisor ='عمر الصديق عبد الله موسى' where supervisor like '%عمر الصديق عبد الله%';
update papers_all set supervisor ='عوض الكريم عوض الله الزين' where supervisor like '%عوض الكريم عوض الله%';
update papers_all set supervisor ='كلود لموند' where supervisor like '%كلود ليموند%';
update papers_all set supervisor ='كمال محمد جاه الله الخضر' where supervisor like '%كمال محمد جاه الله%';
update papers_all set supervisor ='مبارك حسين نجم الدين بشير' where supervisor like '%مبارك حسين نجم الدين%';
update papers_all set supervisor ='محمد أحمد إبراهيم فضل المولى' where supervisor like '%محمد أحمد إبراهيم المولى%';
update papers_all set supervisor ='محمد حسن محمد' where supervisor like '%محمد جسن محمد%';
update papers_all set supervisor ='محمد داؤد محمد داؤد' where supervisor like '%محمد داوود محمد داوود%';
update papers_all set supervisor ='محمد علي أحمد عمر' where supervisor like '%محمد على أحمد عمر%';
update papers_all set supervisor ='محمد علي أحمد عمر' where supervisor= 'محمد على';
update papers_all set supervisor ='محمد حسن محمد' where supervisor= 'محمد حسن';
update papers_all set supervisor ='محمد غالب عبد الرحمن وراق' where supervisor like '%محمد غالب عبد الرحمن%';
update papers_all set supervisor ='محمد مهدي أحمد' where supervisor like '%محمد مهدي احمد%';
update papers_all set supervisor ='نصر سلمان نصر' where supervisor like '%نصر سليمان نصر%';
update papers_all set supervisor ='وداعة محمد الحسن عكود' where supervisor like '%وداعة محمد الحسن%';
update papers_all set supervisor ='ياسر جبريل معاذ' where supervisor like '%ياسر جبريل معاز%';
update papers_all set supervisor ='ياسر عبد المطلب أحمد' where supervisor like '%ياسر عبد المطلب%';
update papers_all set supervisor ='ياسر عبد المطلب أحمد' where supervisor like '%ياسر عبد المنطلب%';
update papers_all set supervisor ='يحيى هارون محمد' where supervisor like '%يحيي هارون محمد%';
update papers_all set supervisor ='ياسر عبد المطلب أحمد' where supervisor like '%ساسر عبد المطلب أحمد%';
update papers_all set supervisor ='سعد حسن أحمد' where supervisor like '%سعد أحمد حسن%';
update papers_all set supervisor ='الفاتح على النور على' where supervisor like '%الفاتح على النور%';


-- // cleaning degree //--
update papers_all set "degree" ='ماجستير' where "degree" like '%ماجتسير%';
update papers_all set "degree" ='ماجستير' where "degree" like '%ماجسنير%';
update papers_all set "others" ='95 ص' where "degree" like '%95 ص%';
update papers_all set "degree" ='' where "degree" like '%95 ص%';

